version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
    ports:
      - '9001:8080'
      - '9002:50000'
    volumes:
      - './jenkins_home:/var/jenkins_home'