version: '3'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - "./data/db:/var/lib/mysql"    
      - "./conf:/etc/mysql/conf.d"
    networks:
      - net
networks:
  net:
    external: true